[tools]
pre-commit = '4.6.1'
terraform = '1.10.1'
terraform-docs = '0.19.0'

[tasks.tf-docs]
run = "terraform-docs --config=.terraform-docs.yaml ."

[tasks.test]
run = "terraform test"

[tasks.fmt]
run = "terraform fmt -recursive"